import { atom } from 'nanostores';

export type Language = 'en' | 'th';

export const currentLanguage = atom<Language>('th');

export const translations = {
  en: {
    // Navigation
    services: 'Services',
    features: 'Features',
    contact: 'Contact',
    bookNow: 'Book Now',
    
    // Hero Section
    heroTitle: 'Book Services',
    heroSubtitle: 'Seamlessly',
    heroDescription: 'The ultimate booking platform for Personal Trainers, Retail, Events, and more.',
    heroTagline: 'Enterprise-grade. Simple to use.',
    trustedBy: 'Trusted by 10,000+ businesses',
    startBookingNow: 'Start Booking Now',
    exploreServices: 'Explore Services',
    activeUsers: 'Active Users',
    uptime: 'Uptime',
    support: 'Support',
    
    // Services Section
    ourServices: 'Our Services',
    servicePortfolio: 'Complete Service Portfolio',
    servicesDescription: 'Choose from our comprehensive range of professional services designed to meet your every need with enterprise-grade reliability.',
    personalTraining: 'Personal Training',
    personalTrainingDesc: 'Book professional personal trainers for customized fitness programs tailored to your goals and lifestyle.',
    retailServices: 'Retail Services',
    retailServicesDesc: 'Schedule shopping appointments and retail consultations with dedicated personal service representatives.',
    eventTickets: 'Event Tickets',
    eventTicketsDesc: 'Book tickets for events, concerts, and activities with instant confirmation and digital delivery.',
    professionalServices: 'Professional Services',
    professionalServicesDesc: 'Book various professional services including meeting rooms, classes, spa treatments, and consultations.',
    mostPopular: '⭐ Most Popular',
    customPrograms: 'Custom Programs',
    certifiedTrainers: 'Certified Trainers',
    progressTracking: 'Progress Tracking',
    personalShopping: 'Personal Shopping',
    skipQueue: 'Skip the Queue',
    consultation247: '24/7 Consultation',
    digitalTickets: 'Digital Tickets',
    freeCancellation: 'Free Cancellation',
    bestPrices: 'Best Prices',
    wideSelection: 'Wide Selection',
    easyBooking: 'Easy Booking',
    flexibleScheduling: 'Flexible Scheduling',
    notSureService: 'Not sure which service fits your needs?',
    expertConsultants: 'Our expert consultants are here to help you find the perfect solution for your requirements.',
    getFreeConsultation: 'Get Free Consultation',
    
    // Service titles and descriptions
    trainerTitle: 'Personal Training',
    trainerDesc: 'Book professional personal trainers for customized fitness programs tailored to your goals and lifestyle.',
    retailTitle: 'Retail Services', 
    retailDesc: 'Schedule shopping appointments and retail consultations with dedicated personal service representatives.',
    ticketTitle: 'Event Tickets',
    ticketDesc: 'Book tickets for events, concerts, and activities with instant confirmation and digital delivery.',
    otherTitle: 'Professional Services',
    otherDesc: 'Book various professional services including meeting rooms, classes, spa treatments, and consultations.',
    
    // Feature translations
    feature1Title: 'Intuitive Interface',
    feature1Desc: 'Beautifully designed UI/UX that\'s simple to use, suitable for everyone from tech-savvy users to seniors.',
    feature2Title: 'Bank-Level Security', 
    feature2Desc: 'Enterprise-grade security with end-to-end encryption. Your data is protected with the highest standards.',
    feature3Title: '24/7 Expert Support',
    feature3Desc: 'Our dedicated support team is available around the clock, every day of the year to assist you.',
    feature4Title: 'Cross-Platform Access',
    feature4Desc: 'Seamlessly works across all devices - mobile, tablet, and desktop. Access anywhere, anytime.',
    feature5Title: 'Flexible Payments',
    feature5Desc: 'Multiple payment options including credit cards, QR codes, bank transfers, and digital wallets.',
    feature6Title: 'Free Cancellation',
    feature6Desc: 'Cancel your bookings for free with no fees when you notify us 24 hours in advance.',
    
    // Service feature translations
    customprograms: 'Custom Programs',
    certifiedtrainers: 'Certified Trainers',
    progresstracking: 'Progress Tracking',
    personalshopping: 'Personal Shopping',
    skipthequeue: 'Skip the Queue',
    '247consultation': '24/7 Consultation',
    digitaltickets: 'Digital Tickets',
    freecancellation: 'Free Cancellation',
    bestprices: 'Best Prices',
    wideselection: 'Wide Selection',
    easybooking: 'Easy Booking',
    flexiblescheduling: 'Flexible Scheduling',
    
    // Features Section
    whyChoose: 'Why Choose',
    enterpriseFeatures: 'Enterprise Features',
    featuresDescription: 'Experience the next generation of booking technology with features designed for modern businesses and demanding users who expect excellence.',
    intuitiveInterface: 'Intuitive Interface',
    intuitiveDesc: 'Beautifully designed UI/UX that\'s simple to use, suitable for everyone from tech-savvy users to seniors.',
    bankLevelSecurity: 'Bank-Level Security',
    securityDesc: 'Enterprise-grade security with end-to-end encryption. Your data is protected with the highest standards.',
    expertSupport: '24/7 Expert Support',
    supportDesc: 'Our dedicated support team is available around the clock, every day of the year to assist you.',
    crossPlatform: 'Cross-Platform Access',
    platformDesc: 'Seamlessly works across all devices - mobile, tablet, and desktop. Access anywhere, anytime.',
    flexiblePayments: 'Flexible Payments',
    paymentsDesc: 'Multiple payment options including credit cards, QR codes, bank transfers, and digital wallets.',
    cancellationFree: 'Free Cancellation',
    cancellationDesc: 'Cancel your bookings for free with no fees when you notify us 24 hours in advance.',
    freeToStart: 'Free to Start',
    startFree: 'Start Using BookingWhale Free',
    freeDescription: 'No setup fees, no monthly subscriptions, no hidden costs. Pay only when you book services. It\'s that simple.',
    noSetupFees: 'No Setup Fees',
    noMonthlyFees: 'No Monthly Fees',
    payPerBooking: 'Pay Per Booking',
    startFreeToday: 'Start Free Today',
    
    // Booking Modal
    chooseService: 'Choose Your Service',
    modalDescription: 'Start your seamless booking experience in just a few clicks',
    personalTrainingModal: 'Personal Training',
    personalTrainingModalDesc: 'Professional fitness coaching and personalized workout programs',
    retailServicesModal: 'Retail Services',
    retailServicesModalDesc: 'Personal shopping and retail consultations with experts',
    eventTicketsModal: 'Event Tickets',
    eventTicketsModalDesc: 'Book tickets for concerts, events, and entertainment',
    professionalServicesModal: 'Professional Services',
    professionalServicesModalDesc: 'Meeting rooms, classes, spa treatments, and more',
    needHelp: 'Need Help?',
    expertConsultantsAvailable: 'Our expert consultants are available to assist you',
    callBooking: 'Call 080-595-6458',
    
    // Footer
    footerDescription: 'The most comprehensive booking platform for professional services. Trusted by thousands of businesses worldwide for reliability and excellence.',
    readyToStart: 'Ready to Get Started?',
    experienceFuture: 'Experience the Future of Booking',
    footerCtaDescription: 'Join thousands of satisfied customers who trust BookingWhale for their service booking needs. Start your journey today, completely free.',
    startBookingNowFooter: 'Start Booking Now',
    callUs: 'Call Us',
    available247: 'Available 24/7',
    responseTime: 'Response within 2 hours',
    businessHours: 'Monday - Friday: 9:00 AM - 6:00 PM',
    weekendHours: 'Weekend: 10:00 AM - 4:00 PM',
    timeZone: 'All times EST',
    allRightsReserved: 'All rights reserved.',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    cookiePolicy: 'Cookie Policy'
  },
  th: {
    // Navigation
    services: 'บริการ',
    features: 'คุณสมบัติ',
    contact: 'ติดต่อ',
    bookNow: 'จองเลย',
    
    // Hero Section
    heroTitle: 'จองบริการ',
    heroSubtitle: 'ได้ง่ายในคลิกเดียว',
    heroDescription: 'แพลตฟอร์มการจองบริการที่ครบครัน สำหรับ Personal Trainer, ร้านค้า, อีเวนต์ และอื่นๆ',
    heroTagline: 'ระดับองค์กร ใช้งานง่าย',
    trustedBy: 'ได้รับความไว้วางใจจากธุรกิจกว่า 10,000 แห่ง',
    startBookingNow: 'เริ่มจองตอนนี้',
    exploreServices: 'ดูบริการทั้งหมด',
    activeUsers: 'ผู้ใช้งาน',
    uptime: 'อัพไทม์',
    support: 'ซัพพอร์ต',
    
    // Services Section
    ourServices: 'บริการของเรา',
    servicePortfolio: 'บริการครบครัน',
    servicesDescription: 'เลือกจากบริการมืออาชีพที่หลากหลาย ออกแบบมาเพื่อตอบสนองทุกความต้องการด้วยคุณภาพระดับองค์กร',
    personalTraining: 'เทรนเนอร์ส่วนตัว',
    personalTrainingDesc: 'จองเทรนเนอร์มืออาชีพสำหรับโปรแกรมฟิตเนสเฉพาะตัว ที่ออกแบบตามเป้าหมายและไลฟ์สไตล์ของคุณ',
    retailServices: 'บริการร้านค้า',
    retailServicesDesc: 'นัดหมายช้อปปิ้งและปรึกษาจากผู้เชี่ยวชาญด้านค้าปลีกส่วนตัว',
    eventTickets: 'ตั๋วอีเวนต์',
    eventTicketsDesc: 'จองตั๋วงานอีเวนต์ คอนเสิร์ต และกิจกรรมต่างๆ พร้อมการยืนยันทันทีและส่งดิจิทัล',
    professionalServices: 'บริการมืออาชีพ',
    professionalServicesDesc: 'จองบริการมืออาชีพต่างๆ รวมถึงห้องประชุม คลาสเรียน สปา และการปรึกษา',
    mostPopular: '⭐ ยอดนิยม',
    customPrograms: 'โปรแกรมเฉพาะตัว',
    certifiedTrainers: 'เทรนเนอร์ที่ได้รับการรับรอง',
    progressTracking: 'ติดตามผลการออกกำลังกาย',
    personalShopping: 'ช้อปปิ้งส่วนตัว',
    skipQueue: 'ไม่ต้องรอคิว',
    consultation247: 'ปรึกษาได้ 24/7',
    digitalTickets: 'ตั๋วดิจิทัล',
    freeCancellation: 'ยกเลิกฟรี',
    bestPrices: 'ราคาดีที่สุด',
    wideSelection: 'บริการหลากหลาย',
    easyBooking: 'จองง่าย',
    flexibleScheduling: 'ยืดหยุ่นเรื่องเวลา',
    notSureService: 'ไม่แน่ใจว่าบริการไหนเหมาะกับคุณ?',
    expertConsultants: 'ทีมผู้เชี่ยวชาญของเราพร้อมช่วยเหลือคุณค้นหาโซลูชั่นที่เหมาะสมที่สุด',
    getFreeConsultation: 'ปรึกษาฟรี',
    
    // Service titles and descriptions
    trainerTitle: 'เทรนเนอร์ส่วนตัว',
    trainerDesc: 'จองเทรนเนอร์มืออาชีพสำหรับโปรแกรมฟิตเนสเฉพาะตัว ที่ออกแบบตามเป้าหมายและไลฟ์สไตล์ของคุณ',
    retailTitle: 'บริการร้านค้า', 
    retailDesc: 'นัดหมายช้อปปิ้งและปรึกษาจากผู้เชี่ยวชาญด้านค้าปลีกส่วนตัว',
    ticketTitle: 'ตั๋วอีเวนต์',
    ticketDesc: 'จองตั๋วงานอีเวนต์ คอนเสิร์ต และกิจกรรมต่างๆ พร้อมการยืนยันทันทีและส่งดิจิทัล',
    otherTitle: 'บริการมืออาชีพ',
    otherDesc: 'จองบริการมืออาชีพต่างๆ รวมถึงห้องประชุม คลาสเรียน สปา และการปรึกษา',
    
    // Feature translations
    feature1Title: 'ใช้งานง่าย',
    feature1Desc: 'ออกแบบ UI/UX ที่สวยงามและใช้งานง่าย เหมาะสำหรับทุกคนตั้งแต่ผู้ใช้เทคโนโลยีจนถึงผู้สูงอายุ',
    feature2Title: 'ความปลอดภัยระดับธนาคาร', 
    feature2Desc: 'ความปลอดภัยระดับองค์กรพร้อมการเข้ารหัสแบบ end-to-end ข้อมูลของคุณได้รับการปกป้องด้วยมาตรฐานสูงสุด',
    feature3Title: 'ซัพพอร์ตผู้เชี่ยวชาญ 24/7',
    feature3Desc: 'ทีมซัพพอร์ตเฉพาะทางของเราพร้อมให้บริการตลอด 24 ชั่วโมง ทุกวันในสัปดาห์',
    feature4Title: 'ใช้งานได้ทุกแพลตฟอร์ม',
    feature4Desc: 'ทำงานได้อย่างราบรื่นบนทุกอุปกรณ์ - มือถือ แท็บเล็ต และเดสก์ท็อป เข้าถึงได้ทุกที่ทุกเวลา',
    feature5Title: 'ชำระเงินยืดหยุ่น',
    feature5Desc: 'ตัวเลือกการชำระเงินหลากหลาย รวมถึงบัตรเครดิต QR Code โอนธนาคาร และกระเป๋าเงินดิจิทัล',
    feature6Title: 'ยกเลิกฟรี',
    feature6Desc: 'ยกเลิกการจองฟรีโดยไม่มีค่าธรรมเนียม เมื่อแจ้ง 24 ชั่วโมงล่วงหน้า',
    
    // Service feature translations
    customprograms: 'โปรแกรมเฉพาะตัว',
    certifiedtrainers: 'เทรนเนอร์ที่ได้รับการรับรอง',
    progresstracking: 'ติดตามผลการออกกำลังกาย',
    personalshopping: 'ช้อปปิ้งส่วนตัว',
    skipthequeue: 'ไม่ต้องรอคิว',
    '247consultation': 'ปรึกษาได้ 24/7',
    digitaltickets: 'ตั๋วดิจิทัล',
    freecancellation: 'ยกเลิกฟรี',
    bestprices: 'ราคาดีที่สุด',
    wideselection: 'บริการหลากหลาย',
    easybooking: 'จองง่าย',
    flexiblescheduling: 'ยืดหยุ่นเรื่องเวลา',
    
    // Features Section
    whyChoose: 'ทำไมต้องเลือก',
    enterpriseFeatures: 'คุณสมบัติระดับองค์กร',
    featuresDescription: 'สัมผัสเทคโนโลยีการจองรุ่นใหม่ด้วยคุณสมบัติที่ออกแบบมาสำหรับธุรกิจสมัยใหม่และผู้ใช้ที่คาดหวังความเป็นเลิศ',
    intuitiveInterface: 'ใช้งานง่าย',
    intuitiveDesc: 'ออกแบบ UI/UX ที่สวยงามและใช้งานง่าย เหมาะสำหรับทุกคนตั้งแต่ผู้ใช้เทคโนโลยีจนถึงผู้สูงอายุ',
    bankLevelSecurity: 'ความปลอดภัยระดับธนาคาร',
    securityDesc: 'ความปลอดภัยระดับองค์กรพร้อมการเข้ารหัสแบบ end-to-end ข้อมูลของคุณได้รับการปกป้องด้วยมาตรฐานสูงสุด',
    expertSupport: 'ซัพพอร์ตผู้เชี่ยวชาญ 24/7',
    supportDesc: 'ทีมซัพพอร์ตเฉพาะทางของเราพร้อมให้บริการตลอด 24 ชั่วโมง ทุกวันในสัปดาห์',
    crossPlatform: 'ใช้งานได้ทุกแพลตฟอร์ม',
    platformDesc: 'ทำงานได้อย่างราบรื่นบนทุกอุปกรณ์ - มือถือ แท็บเล็ต และเดสก์ท็อป เข้าถึงได้ทุกที่ทุกเวลา',
    flexiblePayments: 'ชำระเงินยืดหยุ่น',
    paymentsDesc: 'ตัวเลือกการชำระเงินหลากหลาย รวมถึงบัตรเครดิต QR Code โอนธนาคาร และกระเป๋าเงินดิจิทัล',
    cancellationFree: 'ยกเลิกฟรี',
    cancellationDesc: 'ยกเลิกการจองฟรีโดยไม่มีค่าธรรมเนียม เมื่อแจ้ง 24 ชั่วโมงล่วงหน้า',
    freeToStart: 'เริ่มต้นฟรี',
    startFree: 'เริ่มใช้ BookingWhale ฟรี',
    freeDescription: 'ไม่มีค่าติดตั้ง ไม่มีค่าสมาชิกรายเดือน ไม่มีค่าใช้จ่ายซ่อนเร้น จ่ายเฉพาะเมื่อจองบริการเท่านั้น',
    noSetupFees: 'ไม่มีค่าติดตั้ง',
    noMonthlyFees: 'ไม่มีค่ารายเดือน',
    payPerBooking: 'จ่ายตามการจอง',
    startFreeToday: 'เริ่มฟรีวันนี้',
    
    // Booking Modal
    chooseService: 'เลือกบริการของคุณ',
    modalDescription: 'เริ่มการจองที่ราบรื่นในไม่กี่คลิก',
    personalTrainingModal: 'เทรนเนอร์ส่วนตัว',
    personalTrainingModalDesc: 'โค้ชฟิตเนสมืออาชีพและโปรแกรมออกกำลังกายเฉพาะบุคคล',
    retailServicesModal: 'บริการร้านค้า',
    retailServicesModalDesc: 'ช้อปปิ้งส่วนตัวและปรึกษาร้านค้าพร้อมผู้เชี่ยวชาญ',
    eventTicketsModal: 'ตั๋วอีเวนต์',
    eventTicketsModalDesc: 'จองตั๋วคอนเสิร์ต อีเวนต์ และความบันเทิง',
    professionalServicesModal: 'บริการมืออาชีพ',
    professionalServicesModalDesc: 'ห้องประชุม คลาสเรียน สปา และอื่นๆ',
    needHelp: 'ต้องการความช่วยเหลือ?',
    expertConsultantsAvailable: 'ผู้เชี่ยวชาญของเราพร้อมให้ความช่วยเหลือ',
    callBooking: 'โทร 080-595-6458',
    
    // Footer
    footerDescription: 'แพลตฟอร์มการจองบริการที่ครอบคลุมที่สุดสำหรับบริการมืออาชีพ ได้รับความไว้วางใจจากธุรกิจหลายพันแห่งทั่วโลก',
    readyToStart: 'พร้อมเริ่มต้นแล้วหรือยัง?',
    experienceFuture: 'สัมผัสอนาคตของการจอง',
    footerCtaDescription: 'เข้าร่วมกับลูกค้าหลายพันคนที่พึงพอใจที่วางใจ BookingWhale สำหรับความต้องการการจองบริการ เริ่มต้นการเดินทางของคุณวันนี้ ฟรี',
    startBookingNowFooter: 'เริ่มจองตอนนี้',
    callUs: 'โทรหาเรา',
    available247: 'พร้อมบริการ 24/7',
    responseTime: 'ตอบกลับภายใน 2 ชั่วโมง',
    businessHours: 'จันทร์ - ศุกร์: 09:00 - 18:00 น.',
    weekendHours: 'วันหยุดสุดสัปดาห์: 10:00 - 16:00 น.',
    timeZone: 'เวลาประเทศไทย',
    allRightsReserved: 'สงวนลิขสิทธิ์',
    privacyPolicy: 'นโยบายความเป็นส่วนตัว',
    termsOfService: 'ข้อกำหนดการใช้บริการ',
    cookiePolicy: 'นโยบายคุกกี้'
  }
};

export function t(key: keyof typeof translations.en): string {
  const lang = currentLanguage.get();
  return translations[lang][key] || translations.en[key];
}